#
# Fixed Point Math Macro Library - Makefile
#
# (C)opyright 2005 by Ivo van Poorten
# Licensed under version 2 of the GPL
#
# $Id$
#

include ../config.mak

.PHONY:	clean
clean:


.PHONY:	distclean
distclean:		clean
	rm -f *~

